title: Sanyapoom Sirijirakarn (Safe) # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  About Me
  <br><br>
  I am a student in Seattle Pacific University majoring in Computer Science BS.
  I hope to use my skills in art, design, and programming to create intuitive software 
  to improve our daily life.
  <br><br>
  My personal interests are game development, machine learning, database, and server management.
  <br><br>
  <a href="https://www.linkedin.com/in/sanyapoom-sirijirakarn-763450161/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
